services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pessoa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST_NAME: postgresql
      RABBITMQ_HOST_NAME: rabbitmq
      CSV_DIRETORIO: /app/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      BACKEND_HOST_NAME: backend