services:
  postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pessoa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres