spring:
  application:
    name: emiteai-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/pessoa_db?createDatabaseIfNotExists=true
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

csv:
  diretorio: ${CSV_DIRETORIO:./csv}