spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:5432/pessoa_db?createDatabaseIfNotExists=true
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST_NAME:localhost}
    port: 5672
    username: guest
    password: guest

csv:
  diretorio: ${CSV_DIRETORIO:./csv}