### Cadastrar pessoa
POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "nome": "Thiago",
  "cpf": "542.817.540-08",
  "endereco": {
    "numero": "100",
    "complemento": "Teste",
    "cep": "12.222-963",
    "bairro": "Bairro das flores",
    "municipio": "Gaspar",
    "estado": "SC"
  }
}

### Atualizar pessoa
PUT http://localhost:8080/pessoas/1
Content-Type: application/json

{
  "nome": "Thiago Cesar",
  "cpf": "781.415.490-14",
  "endereco": {
    "numero": "104",
    "complemento": "Complemento do endereço",
    "cep": "12.222-444",
    "bairro": "Bairro do endereço",
    "municipio": "Blumenau",
    "estado": "SC"
  }
}

### Deletar pessoa
DELETE http://localhost:8080/pessoas/1