### Cadastrar pessoa
POST http://localhost:8080/pessoas
Content-Type: application/json

{
  "nome": "Márcia",
  "cpf": "154.698.090-30",
  "endereco": {
    "numero": "400",
    "complemento": "Teste",
    "cep": "12.222-963",
    "bairro": "Bairro",
    "municipio": "Florianópolis",
    "estado": "SC"
  }
}

### Atualizar pessoa
PUT http://localhost:8080/pessoas/1
Content-Type: application/json

{
  "nome": "Thiago Cesar",
  "cpf": "781.415.490-14",
  "endereco": {
    "numero": "104",
    "complemento": "Complemento do endereço",
    "cep": "12.222-444",
    "bairro": "Bairro do endereço",
    "municipio": "Blumenau",
    "estado": "SC"
  }
}

### Deletar pessoa
DELETE http://localhost:8080/pessoas/1

### Listar todas as pessoas paginado
GET http://localhost:8080/pessoas

### Detalhar pessoa
GET http://localhost:8080/pessoas/3